version: '3'
services:
  redis:
    image: "redis:alpine"
    ports: 
    - "6379:6379"
  web-server:
    depends_on:
    - redis
    build: ./web-server
    ports:
    - "5000:5000"
    environment:
    - PORT=5000
    - UPLOAD_LOCATION=uploads
    - REDIS_HOST=redis
  worker:
    depends_on:
    - redis
    build: ./worker
    environment:
    - WORKERS=3
    - REDIS_HOST=redis:6379

      
